credentials:
  usernames:
    demo:
      email: demo@example.com
      name: Demo User
      password: $2b$12$r6yKzZ7H3jJk7V8L9wYzXeJkLmNpQrStUvWxYzAbCdEfGhIjKlMnO
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$r6yKzZ7H3jJk7V8L9wYzXeJkLmNpQrStUvWxYzAbCdEfGhIjKlMnO
cookie:
  expiry_days: 30
  key: neurosegment_auth_key
  name: neurosegment_cookie